---
title: "Figure 3B"   
output: html_document
---

## caculate delta
```{r}
Mul_ccm_obs_all <- read.csv( "01_data/02_mul_ccm_lag0-3_obs.csv")

filtered_ccm <- Mul_ccm_obs_all %>%
  filter(grepl("ir", var_col))

baseline <- Mul_ccm_obs_all %>%
  filter(var_num == 1)%>%
  select(country, rho, MAE, RMSE) %>%
  distinct(country, .keep_all = TRUE)

result <- Mul_ccm_obs_all %>%
  filter(var_num > 1) %>%
  select(country, var_col, rho, MAE, RMSE)

delta_Mul_ccm_obs <- result %>%
  left_join(baseline, by = "country", suffix = c("", "_baseline")) %>%
  mutate(
    delta_rho = rho - rho_baseline,
    delta_MAE = MAE - MAE_baseline,
    delta_RMSE = RMSE - RMSE_baseline
  ) %>%
  select(-rho_baseline, -MAE_baseline, -RMSE_baseline)


delta_obs_95ci <- delta_Mul_ccm_obs %>%
  group_by(var_col) %>%
  summarise(
    delta_rho_mean = mean(delta_rho),
    delta_rho_ci_lower = quantile(delta_rho, 0.025),
    delta_rho_ci_upper = quantile(delta_rho, 0.975),
    
    delta_RMSE_mean = mean(delta_RMSE),
    delta_RMSE_ci_lower = quantile(delta_RMSE, 0.025),
    delta_RMSE_ci_upper = quantile(delta_RMSE, 0.975),    
  ) %>%
  arrange(match(var_col, delta_Mul_ccm_obs$var_col))


#write.csv(delta_obs_95ci, "01_EDM_Dengue-main/02_output/02_CCM/03_mul_CCM/02-1_lag0-3_obs_delta.csv")
```

mul cmm with ebusizaki null model
```{r}
Mul_ccm_ebi_all <- read.csv( "01_data/02_output/03_mul_ccm_lag0-3_ebi.csv")
num_var_col_categories_all <- length(unique(Mul_ccm_ebi_all$var_col))

Mul_ccm_ebi_all <- Mul_ccm_ebi_all %>%
  group_by(country) %>%
  mutate(sur_num = (row_number() - 1) %/% num_var_col_categories_all + 1)


baseline <- Mul_ccm_ebi_all %>%
  filter(E == 1)%>%
  select(country, sur_num, rho, mae, rmse) %>%
  distinct(country, .keep_all = TRUE)

result <- Mul_ccm_ebi_all %>%
  filter(E > 1) %>%
  select(country, sur_num, var_col, rho, mae, rmse)

delta_Mul_ccm_ebi <- result %>%
  left_join(baseline, by = c("country", "sur_num"), suffix = c("", "_baseline")) %>%
  mutate(
    delta_rho = rho - rho_baseline,
    delta_MAE = mae - mae_baseline,
    delta_RMSE = rmse - rmse_baseline
  ) %>%
  select(-rho_baseline, -mae_baseline, -rmse_baseline)

delta_ebi_95ci <- delta_Mul_ccm_ebi %>%
  group_by(var_col) %>%
  summarise(
    delta_rho_mean = mean(delta_rho, na.rm = TRUE),
    delta_rho_ci_lower = quantile(delta_rho, 0.025, na.rm = TRUE),
    delta_rho_ci_upper = quantile(delta_rho, 0.975, na.rm = TRUE),
    
    delta_RMSE_mean = mean(delta_RMSE, na.rm = TRUE),
    delta_RMSE_ci_lower = quantile(delta_RMSE, 0.025, na.rm = TRUE),
    delta_RMSE_ci_upper = quantile(delta_RMSE, 0.975, na.rm = TRUE)    
  ) %>%
  arrange(match(var_col, delta_Mul_ccm_ebi$var_col))

#write.csv(delta_ebi_95ci, "01_EDM_Dengue-main/02_output/02_CCM/03_mul_CCM/02-2_lag0-3_ebi_delta.csv")
```

mul cmm with seasonal null model
```{r}
Mul_ccm_sea_all <- read.csv( "01_data/02_output/04_mul_ccm_lag0-3_sea.csv")
num_var_col_categories_all <- length(unique(Mul_ccm_sea_all$var_col))

Mul_ccm_sea_all <- Mul_ccm_sea_all %>%
  group_by(country) %>%
  mutate(sur_num = (row_number() - 1) %/% num_var_col_categories_all + 1)#%>%


baseline <- Mul_ccm_sea_all %>%
  filter(E == 1)%>%
  select(country, sur_num, rho, mae, rmse) %>%
  distinct(country, .keep_all = TRUE)

result <- Mul_ccm_sea_all %>%
  filter(E > 1) %>%
  select(country, sur_num, var_col, rho, mae, rmse)

delta_Mul_ccm_sea <- result %>%
  left_join(baseline, by = c("country", "sur_num"), suffix = c("", "_baseline")) %>%
  mutate(
    delta_rho = rho - rho_baseline,
    delta_MAE = mae - mae_baseline,
    delta_RMSE = rmse - rmse_baseline
  ) %>%
  select(-rho_baseline, -mae_baseline, -rmse_baseline)

delta_sea_95ci <- delta_Mul_ccm_sea %>%
  group_by(var_col) %>%
  summarise(
    delta_rho_mean = mean(delta_rho, na.rm = TRUE),
    delta_rho_ci_lower = quantile(delta_rho, 0.025, na.rm = TRUE),
    delta_rho_ci_upper = quantile(delta_rho, 0.975, na.rm = TRUE),
    
    delta_RMSE_mean = mean(delta_RMSE, na.rm = TRUE),
    delta_RMSE_ci_lower = quantile(delta_RMSE, 0.025, na.rm = TRUE),
    delta_RMSE_ci_upper = quantile(delta_RMSE, 0.975, na.rm = TRUE)    
  ) %>%
  arrange(match(var_col, delta_Mul_ccm_sea$var_col))


#write.csv(delta_sea_95ci, "01_EDM_Dengue-main/02_output/02_CCM/03_mul_CCM/02-3_lag0-3_sea_delta.csv")
```



## plot Fig_3B
```{r}

delta_obs_95ci$var_col <- factor(delta_obs_95ci$var_col, levels = unique(delta_obs_95ci$var_col))

max_mean <- max(delta_obs_95ci$delta_rho_ci_upper, delta_sea_95ci$delta_rho_ci_upper, delta_ebi_95ci$delta_rho_ci_upper)
min_mean <- min(delta_obs_95ci$delta_rho_ci_lower, delta_sea_95ci$delta_rho_ci_lower, delta_ebi_95ci$delta_rho_ci_lower)
max_level <- max(delta_obs_95ci$delta_rho_mean)

max_ci_upper <- ceiling( max_mean * 10) / 10 
min_ci_upper <- floor( min_mean * 10) / 10
plot_mul_ccm_95ci <- ggplot(delta_obs_95ci, aes(x = var_col, y = delta_rho_mean, color = "black")) +
  geom_errorbar(aes(ymin = delta_rho_ci_lower, ymax = delta_rho_ci_upper), color = c_grey, width = 0.3, size = 0.9) +
  geom_point(color = c_grey, size = 3, stroke = 1) +
  geom_point(data = delta_sea_95ci, aes(x = var_col, y = delta_rho_mean), color = c_green, size = 3, stroke = 1) +
    geom_errorbar(data = delta_sea_95ci,aes(ymin = delta_rho_ci_lower, ymax = delta_rho_ci_upper), color = c_green, width = 0.3, size = 0.9) +
  geom_point(data = delta_ebi_95ci, aes(x = var_col, y = delta_rho_mean), color = c_blue, size = 3, stroke = 1) + 
    geom_errorbar(data = delta_ebi_95ci, aes(ymin = delta_rho_ci_lower, ymax = delta_rho_ci_upper), color = c_blue, width = 0.3, size = 0.9) +
  geom_hline(yintercept = max_level, linetype = "dashed", color = "grey") +  
  coord_cartesian(ylim = c(min_ci_upper, max_ci_upper)) +
  scale_y_continuous(name = "Improved cross mapping skill (p)", breaks = round(seq(min_ci_upper, max_ci_upper, 0.1), 1)) +
  scale_x_discrete(name = "Driver") +
  labs(y = NULL, color = "", fill = "") +
  mytheme +
  scale_fill_manual(name = '', values = "black") +
  scale_color_manual(name = "",
                       values = c(c_red,c_blue),
                       labels = c("Seasonal null model", 
                                  "Ebisuzaki null model")) +
  theme(strip.background = element_blank(), strip.text = element_text(size = 9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

plot_mul_ccm_95ci
 
file_name <- paste0("02_output/02_Fig3B.pdf")
ggsave(file_name, plot_mul_ccm_95ci, width = 6, height = 4) 

```

