rm(list=ls()) #remove previous variable assignments

library(dplyr)
library(testcorr)
library(ggplot2)
#library(tidyr)
#library(caret)

# Note: Due to the large size of the data files, they are not included in the data folder.
# Instead, they are generated by running the following scripts:
# '03_sim_aeg_with-iobw_20ens.R'
# '04_sim_alb_with-iobw_20ens.R'
# '05_sim_aeg_without-iobw_20ens.R'
# '06_sim_alb_without-iobw_20ens.R'
# These scripts produce the output files needed for the following test.

# Change the file paths according to the country being tested:
ir_data<-read.csv('02_output/01_sim-aeg_with-iobw/2_Bolivia.csv')
ir_data<-read.csv('02_output/02_sim-alb_with-iobw/1_Belize.csv')
ir_data<-read.csv('02_output/03_sim-aeg_without-iobw/2_Bolivia.csv')
ir_data<-read.csv('02_output/04_sim-alb_without-iobw/1_Belize.csv')

#test
ir_best <- subset(ir_data,  time >396)
ans_all <- c()

target_IC <- c(1:50)
target_ID <- c(1:51)
target_ratio <- c(1:25) 

for (ID_j in target_ID) {  
  for (IC_k in target_IC) { 
    for (RATIO_r in target_ratio) {
      ans_temp <- c()
      ir_sim_best_c_spe <- ir_best %>% 
        filter(ID == ID_j & IC==IC_k & ratio==RATIO_r)%>% 
        mutate(pre_cases_std = scale(pre_cases),
               obs_cases_std = scale(obs_cases))
      
      #Calculate the r and p values of obs_cases_std $pre_cases_std
      if(all(ir_sim_best_c_spe$pre_cases == 0)) {
        ans_best <- data.frame("lag" = "0", "R" = "-10", "t_P" = "-10", "t_robust_P" = "-10", "hb_P" = "-10", "hb_robust_P" = "-10")
      } else {
        ans <- cc.test(ir_sim_best_c_spe$pre_cases_std, ir_sim_best_c_spe$obs_cases_std, max.lag = 1, plot = F)
        ans_best <- data.frame("lag" = ans$lag, "R" = round(ans$cc, 3),
                               "t_P" = round(ans$pvt, 3), "t_robust_P" = round(ans$pvttilde, 3),
                               "hb_P" = round(ans$pvhb, 3), "hb_robust_P" = round(ans$pvqtilde, 3)) %>% filter(lag ==0)
      }
      ans_temp <-cbind(IC_k,ID_j,RATIO_r,ans_best)
      ans_all <- rbind(ans_all,ans_temp)
    }
  }
}

# change the following four files according to the tested country
write.csv(ans_all, paste("02_output/01_sim-aeg_with-iobw/2_Bolivia-rp.csv"))
write.csv(ans_all, paste("02_output/02_sim-alb_with-iobw/1_Belize-rp.csv"))
write.csv(ans_all, paste("02_output/03_sim-aeg_without-iobw/2_Bolivia-rp.csv"))
write.csv(ans_all, paste("02_output/04_sim-alb_without-iobw/1_Belize-rp.csv"))